### PR TITLE
Add rule to check whether schema does not use `anyOf` or `oneOf`

### PR DESCRIPTION
**Pull request by mogottsch**
### What does this PR do?

This PR adds a new rule to check whether the schema uses `anyOf` and `oneOf` only for specific purposes as defined in R9 in this [RFC](https://github.com/giantswarm/rfc/pull/55).

### What is the effect of this change to users?

Users that run the `verify` command with the `--rule-set` cluster-app flag will see additional errors.

### How does it look like?

```
❯ go run ./main.go verify --rule-set cluster-app ./pkg/lint/rules/testdata/avoid_x_of/any_of_and_one_of.json
...

Errors (4)

- Schema at path '/age' must only use oneOf for one of the following purposes:
        - Validation constraints: The subschemas cannot be used as validation constraints because they contain the following illegal keywords: type, properties.
        - Deprecation: The subschemas can only be used for deprecation if exactly one subschema is not deprecated and all others are deprecated.
- Schema at path '/foo' must only use anyOf for one of the following purposes:
        - Validation constraints: The subschemas cannot be used as validation constraints because they contain the following illegal keywords: type.
        - Deprecation: The subschemas can only be used for deprecation if exactly one subschema is not deprecated and all others are deprecated.
...
```

### Any background context you can provide?

Towards https://github.com/giantswarm/roadmap/issues/1772
[RFC](https://github.com/giantswarm/rfc/pull/55)

### What is needed from the reviewers?

You can test the changes with:
```
go run ./main.go verify --rule-set cluster-app ./pkg/lint/rules/testdata/avoid_x_of/any_of_and_one_of.json
```
And to verify that a correct usage of `anyOf` and `oneOf` does not produce errors:
```
go run ./main.go verify --rule-set cluster-app ./pkg/lint/rules/testdata/avoid_x_of/correct.json
```

### Do the docs/README need to be updated?

No

### Should this change be mentioned in the release notes?

- [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by marians** [comment]
R9 isn't up-to-date yet. As we discussed on Friday, we will allow anyOf and oneOf, but only for constraints.

**Comment by mogottsch** [comment]
> R9 isn't up-to-date yet. As we discussed on Friday, we will allow anyOf and oneOf, but only for constraints.

Oops, thanks for noticing.

**Comment by marians** [comment]
I just updated R9 in the RFC draft.

**Comment by marians** [comment]
Unsubscribing for now. Please mark as ready for review and re-request review once this is ready.

**Comment by mogottsch** [comment]
@marians ping, because I am not sure whether you saw the re-request for review.

**Review by marians — APPROVED** [review]
Great!

**Pull request merged**
