### PR TITLE
Add rule to check whether properties have exactly one type

### PR DESCRIPTION
**Pull request by mogottsch**
### What does this PR do?

This PR adds a new rule to check all properties have exactly one type as defined by R2 in this [RFC](https://github.com/giantswarm/rfc/pull/55).

### What is the effect of this change to users?

Users that run the `verify` command with the `--rule-set` cluster-app flag will see additional errors.

### How does it look like?

```
Errors (3)

- Property '/replicas' has 2 types, but must have exactly one.
```

### Any background context you can provide?

Towards https://github.com/giantswarm/roadmap/issues/1772
[RFC](https://github.com/giantswarm/rfc/pull/55)

### What is needed from the reviewers?

You can test the changes with:
```
go run ./main.go verify ./pkg/lint/rules/testdata/properties_must_have_one_type/multiple_types.json --rule-set=cluster-app
```

### Do the docs/README need to be updated?

No

### Should this change be mentioned in the release notes?

- [x] CHANGELOG.md has been updated

### CODE REVIEW

**Review by anvddriesch — APPROVED** [review]
LGTM
However, wouldn't there be situations where more than one type is possible?

**Comment by mogottsch** [comment]
> LGTM However, wouldn't there be situations where more than one type is possible?

This constraint mainly is primarily due to the fact that it is really difficult to handle multiple types in the UI.
Are you thinking about any specific examples? I think avoiding multiple types seems manageable.

**Comment by anvddriesch** [comment]
> Are you thinking about any specific examples? 
I don't know any regarding cluster apps. However, for general apps we definitely have some where the `managementCluster` property can be more than one type due to differences between WC and MC setups.
e.g https://github.com/giantswarm/athena/blob/147439d1a132b2bfce8c5da40dbd27ad4c99cc10/helm/athena/values.schema.json#L86-L90

**Comment by marians** [comment]
I checked and we had one use of multiple types, where one of the types was `null`, as a workaround. This has been fixed meanwhile.

**Review by marians — APPROVED** [review]

**Pull request merged**
